@rl = http://localhost:3000
@js = application/json

GET {{rl}}/

###
GET {{rl}}/LIBROS
Content-Type: {{js}}

###
GET {{rl}}/LIBROS/1
Content-Type: {{js}}

###
POST {{rl}}/LIBROS
Content-Type: {{js}}

{
    "id": 1,
    "Titulo": "El nombre del viento",
    "Autor": "Patrick Rothfuss",
    "anio_publicacion": 2007
}
###
DELETE {{rl}}/Libros/1
Content-Type: {{js}}
###