@rl = http://localhost:3000
@js = application/json

GET {{rl}}/

###
GET {{rl}}/LIBROS
Content-Type: {{js}}

###
POST {{rl}}/LIBROS
Content-Type: {{js}}
{
    "id": 1,
    "titulo": "El nombre del viento",
    "autor": "Patrick Rothfuss",
    "anio_publicacion": 2007,
}