@rl = http://localhost:3000
@js = application/json

GET {{rl}}/

###
GET {{rl}}/LIBROS
Content-Type: {{js}}

###
GET {{rl}}/LIBROS/1
Content-Type: {{js}}

###
POST {{rl}}/LIBROS
Content-Type: {{js}}

{
    "id": 1,
    "Titulo": "palanca",
    "Autor": "papablo",
    "Anio_publicacion": 2007,
    "categoria": "aventura"
}
###
DELETE {{rl}}/Libros/1
Content-Type: {{js}}
###

GET {{rl}}/LIBROS?Titulo="palanca"
Content-Type: {{js}}
###
GET {{rl}}/Libros?paginar=1
Content-Type: {{js}}
###
GET {{rl}}/Libros?ordenar=asc
Content-Type: {{js}}